### ISSUE TITLE
Should we automate more conventions?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/stickler#2]
A couple come to mind:

- `['**/__tests__/**', 'test-util/**', 'test/**']` could all have the Jest settings turned on by default. 
- We could always assume `node: true` as a base config unless you specify otherwise.

We would need a different kind of setting to toggle these things. Maybe `jsLint` should be change to an object like this:

```js
{
  settings: {..},
  overrides: [
    { files: [..], settings: {..} }
  ],
  jestOverride: boolean
}
```

By adding a `settings` layer, we'd open up the possibility for options like `jestOverride`.

@mapbox/frontend-platform what do you think?

**Comment by kepta** [comment]
As per our last discussion, we found out that it would be a good idea to get the Jest paths directly from the Jest configuration. Duplicating these paths in stickler and Jest seems redundant. 

Also, what do you think about removing `jsLint.node` option? I don't see why would someone keep `engines` and`jsLint.node` differently.

**Comment by davidtheclark** [comment]
> I don't see why would someone keep engines andjsLint.node differently.

If your package is for the frontend, not Node, it may be a good idea not to specify `engines` in `package.json`. Yarn will make a big stink about `engines`  matching your Node version, and that means that npm or other installers might also make a stink about it in the future.

**Comment by kepta** [comment]
Ahh, makes sense to me.

**Comment by davidtheclark** [comment]
After discussion with @kepta, I have an idea for the next iteration that should make things even more straightforward. Going to take a second to articulate the goal before implementing:

- The default `jsLint` setting with be `node: true` — that is, if you don't provide anything.
- `jsLint` will accept an array of objects, each object with `files` and `settings`. `files` defines glob-arrays, and `settings` the linting settings. 
- There is no "base" config that "overrides" get merged into. Instead, if you want to extend configurations you can do that with `Object.assign` or other native JS features. I'm thinking now that the whole base/overrides distinction was a bad influence from the kind of conventions ESLint's config API established because it wants to run in non-JS files: if we're using a JS configuration, no need to introduce similar patterns.
- For any given file, the first `jsLint` item whose `files` glob-array matches will be used. If the file matches multiple glob-arrays, an error will be thrown, since that should represent a mistake on the user's part.
- If Jest is found in `package.json`, we'll try to automatically add `env.jest` to files that Jest is configured to run against.
