### ISSUE TITLE
Let us provide a dry run option

### ISSUE THREAD

**Issue by kepta** [mapbox/stickler#3]
I think to be able to dry run the `write` process of stickler would be a good idea. 
We can probably display all the files it is going change when running on this mode.

**Comment by davidtheclark** [comment]
Can you say more about what you think the value would be? Do you think you would see the list of files that would be changed and then decide *not* to run format based on that?

**Comment by kepta** [comment]
I was thinking more in light of having this along with `--fix`, but since that isn't moving forward, so we can probably reconsider this when we revisit `--fix`.
